In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [ ]:
dataset_path = '/content/drive/MyDrive/Colab Notebooks/Combined.csv'
df = pd.read_csv(dataset_path)

<ipython-input-3-970b3fbba648>:2: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_path)

In [ ]:
df

,Unnamed: 0,Seq,Dur,RunTime,Mean,Sum,Min,Max,Proto,sTos,...,sVid,dVid,SrcTCPBase,DstTCPBase,TcpRtt,SynAck,AckDat,Label,Attack Type,Attack Tool
0,0,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,icmp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
1,1,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,icmp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
2,2,3,4.998020,4.998020,4.998020,4.998020,4.998020,4.998020,udp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
3,3,4,4.998037,4.998037,4.998037,4.998037,4.998037,4.998037,udp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
4,4,5,4.999453,4.999453,4.999453,4.999453,4.999453,4.999453,udp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215885,487569,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,sctp,186.0,...,610.0,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
1215886,487570,3,0.235607,0.235607,0.235607,0.235607,0.235607,0.235607,sctp,186.0,...,NaN,610.0,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
1215887,487571,764,0.099927,0.099927,0.099927,0.099927,0.099927,0.099927,tcp,0.0,...,NaN,NaN,2.237373e+09,1.983280e+09,0.0,0.0,0.0,Benign,Benign,Benign
1215888,487572,3,1.307852,1.307852,1.307852,1.307852,1.307852,1.307852,sctp,186.0,...,NaN,610.0,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
1215889,487573,1,0.476803,0.476803,0.476803,0.476803,0.476803,0.476803,sctp,186.0,...,610.0,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign

In [ ]:
df.dtypes

Unnamed: 0       int64
Seq              int64
Dur            float64
RunTime        float64
Mean           float64
Sum            float64
Min            float64
Max            float64
Proto           object
sTos           float64
dTos           float64
sDSb            object
dDSb            object
sTtl           float64
dTtl           float64
sHops          float64
dHops          float64
Cause           object
TotPkts          int64
SrcPkts          int64
DstPkts          int64
TotBytes         int64
SrcBytes         int64
DstBytes         int64
Offset           int64
sMeanPktSz     float64
dMeanPktSz     float64
Load           float64
SrcLoad        float64
DstLoad        float64
Loss             int64
SrcLoss          int64
DstLoss          int64
pLoss          float64
SrcGap         float64
DstGap         float64
Rate           float64
SrcRate        float64
DstRate        float64
State           object
SrcWin         float64
DstWin         float64
sVid           float64
dVid           float64
SrcTCPBase     float64
DstTCPBase     float64
TcpRtt         float64
SynAck         float64
AckDat         float64
Label           object
Attack Type     object
Attack Tool     object
dtype: object

In [ ]:
null_col = [key for key in dict(df.isnull().sum().sort_values(ascending=False))
              if dict(df.isnull().sum().sort_values(ascending=False))[key] > 937218]
print(null_col)

['dVid', 'sVid', 'DstWin', 'DstTCPBase', 'SrcWin', 'dDSb', 'dHops', 'dTtl', 'dTos', 'SrcTCPBase', 'DstGap', 'SrcGap']

In [ ]:
df.isnull().sum().sort_values(ascending=False)

dVid           1213881
sVid           1101319
DstWin         1038812
DstTCPBase      985843
SrcWin          973470
dDSb            943067
dHops           943067
dTtl            943067
dTos            943067
SrcTCPBase      937219
DstGap          937219
SrcGap          937219
sTos               214
sDSb               214
sTtl               214
sHops              214
DstRate              0
Rate                 0
SrcRate              0
pLoss                0
DstLoss              0
Unnamed: 0           0
State                0
Loss                 0
TcpRtt               0
SynAck               0
AckDat               0
Label                0
Attack Type          0
SrcLoss              0
dMeanPktSz           0
DstLoad              0
TotPkts              0
Dur                  0
RunTime              0
Mean                 0
Sum                  0
Min                  0
Max                  0
Proto                0
Cause                0
SrcPkts              0
SrcLoad              0
DstPkts              0
TotBytes             0
SrcBytes             0
DstBytes             0
Offset               0
sMeanPktSz           0
Seq                  0
Load                 0
Attack Tool          0
dtype: int64

In [ ]:
#dropping column with greater null values
df.drop(columns = null_col,inplace = True)

In [ ]:
#remaing null columns with less number of null values to be filled with zero
null_col_2 = [key for key in dict(df.isnull().sum().sort_values(ascending=False))
              if dict(df.isnull().sum().sort_values(ascending=False))[key] > 0]
print(null_col_2)

['sTtl', 'sHops', 'sTos', 'sDSb']

In [ ]:
df.loc[:, null_col_2] = df.loc[:, null_col_2].fillna(0)
df.drop(columns = 'Unnamed: 0',inplace = True)

In [ ]:
#performing under sampling

In [ ]:
df['Label'].value_counts()

Malicious    738153
Benign       477737
Name: Label, dtype: int64

In [ ]:
df_be = df[df['Label'] == 'Benign']
df_ma = df[df['Label'] == 'Malicious']

In [ ]:
#selecting 1000 row for both classes
df_be_500 = df_be.iloc[:500]
df_ma_500 = df_ma.iloc[:500]
df_1000 = pd.concat([df_be_500,df_ma_500],ignore_index = True)
df_1000 = df_1000.sample(frac =1).reset_index(drop = True)

In [ ]:
df_1000['Label'].value_counts()

Malicious    500
Benign       500
Name: Label, dtype: int64