In [59]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in a:\anacondainstall\envs\tensorflow\lib\site-packages (1.2.2)
Collecting scikit-learn
  Downloading scikit_learn-1.4.1.post1-cp39-cp39-win_amd64.whl (10.6 MB)
     --------------------------------------- 10.6/10.6 MB 16.4 MB/s eta 0:00:00
Requirement already satisfied: joblib>=1.2.0 in a:\anacondainstall\envs\tensorflow\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: scipy>=1.6.0 in a:\anacondainstall\envs\tensorflow\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: numpy<2.0,>=1.19.5 in a:\anacondainstall\envs\tensorflow\lib\site-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in a:\anacondainstall\envs\tensorflow\lib\site-packages (from scikit-learn) (3.1.0)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'A:\\Anacondainstall\\envs\\tensorflow\\Lib\\site-packages\\~klearn\\.libs\\msvcp140.dll'
Consider using the `--user` option or check the permissions.

In [60]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report

In [61]:
df = pd.read_csv('Combined.csv',low_memory=False)

In [62]:
df

,Unnamed: 0,Seq,Dur,RunTime,Mean,Sum,Min,Max,Proto,sTos,...,sVid,dVid,SrcTCPBase,DstTCPBase,TcpRtt,SynAck,AckDat,Label,Attack Type,Attack Tool
0,0,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,icmp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
1,1,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,icmp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
2,2,3,4.998020,4.998020,4.998020,4.998020,4.998020,4.998020,udp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
3,3,4,4.998037,4.998037,4.998037,4.998037,4.998037,4.998037,udp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
4,4,5,4.999453,4.999453,4.999453,4.999453,4.999453,4.999453,udp,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215885,487569,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,sctp,186.0,...,610.0,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
1215886,487570,3,0.235607,0.235607,0.235607,0.235607,0.235607,0.235607,sctp,186.0,...,NaN,610.0,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
1215887,487571,764,0.099927,0.099927,0.099927,0.099927,0.099927,0.099927,tcp,0.0,...,NaN,NaN,2.237373e+09,1.983280e+09,0.0,0.0,0.0,Benign,Benign,Benign
1215888,487572,3,1.307852,1.307852,1.307852,1.307852,1.307852,1.307852,sctp,186.0,...,NaN,610.0,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign
1215889,487573,1,0.476803,0.476803,0.476803,0.476803,0.476803,0.476803,sctp,186.0,...,610.0,NaN,NaN,NaN,0.0,0.0,0.0,Benign,Benign,Benign

In [63]:
df.drop('Unnamed: 0',axis = 1 ,inplace = True)

In [64]:
df.columns

Index(['Seq', 'Dur', 'RunTime', 'Mean', 'Sum', 'Min', 'Max', 'Proto', 'sTos',
       'dTos', 'sDSb', 'dDSb', 'sTtl', 'dTtl', 'sHops', 'dHops', 'Cause',
       'TotPkts', 'SrcPkts', 'DstPkts', 'TotBytes', 'SrcBytes', 'DstBytes',
       'Offset', 'sMeanPktSz', 'dMeanPktSz', 'Load', 'SrcLoad', 'DstLoad',
       'Loss', 'SrcLoss', 'DstLoss', 'pLoss', 'SrcGap', 'DstGap', 'Rate',
       'SrcRate', 'DstRate', 'State', 'SrcWin', 'DstWin', 'sVid', 'dVid',
       'SrcTCPBase', 'DstTCPBase', 'TcpRtt', 'SynAck', 'AckDat', 'Label',
       'Attack Type', 'Attack Tool'],
      dtype='object')

In [65]:
X = df.copy()
X.drop('Attack Type',inplace = True,axis = 1)
y = df[['Attack Type']]

In [66]:
cat_var = [key for key in dict(X.dtypes)
             if dict(X.dtypes)[key] in ['object'] ]

print(cat_var)

['Proto', 'sDSb', 'dDSb', 'Cause', 'State', 'Label', 'Attack Tool']